name: backup

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create git identity
        run: |
          # https://api.github.com/users/github-actions%5Bbot%5D
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Backup
        run: ./run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        run: |
          git add .
          git commit -m "chore: Update backup."
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
